version: '3.8'

services:
  backend:
    build:
      context: ./code/backend
      dockerfile: Dockerfile
    volumes:
      - ./code/backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    build:
      context: ./code/frontend
    volumes:
      - ./code/frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:8000